// <auto-generated />
namespace SimpleForum.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Forumdbinitialize : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Forumdbinitialize));
        
        string IMigrationMetadata.Id
        {
            get { return "201707111324184_Forum db initialize"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
